---
version: "3"
services:
 devopsdb:
   image: barath1055/myrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: barath1055/myrepo:appimage
   ports:
     - "4321:8080"
   depends_on:
     - "devopsdb"
